/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.interfaces;

import br.com.senac.JPA.Biblioteca;
import br.com.senac.JPA.BibliotecaDAO;
import br.com.senac.JPA.UsuarioDAO;
import br.com.senac.JPA.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Leonardo
 */
public class TelaCadastrar extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form TelaCadastrar
     */
    public TelaCadastrar(Usuario usuario, boolean exibirMensagemBoasVindas) {
        initComponents();
         
        
        BotaoSalvar.setEnabled(false); 
        BotaoListagem.setEnabled(false); 

        this.usuario = usuario;
        this.LabelUsuario.setText("Usuário não informado");

        if (usuario != null) {          
            this.LabelUsuario.setText(usuario.getNome() + " (" + usuario.getTipo() + ")");

            if (exibirMensagemBoasVindas) {
                String mensagem = "Bem-vindo: " + usuario.getNome() + "\nSeu tipo é: " + usuario.getTipo();
                JOptionPane.showMessageDialog(null, mensagem); 
            }

            if (usuario.getTipo().equals("ADMINISTRADOR")) {
                BotaoListagem.setEnabled(true); 
                BotaoSalvar.setEnabled(true); 
            }
             else if (usuario.getTipo().equals("USUARIO")) {
                BotaoListagem.setEnabled(true); 
                BotaoSalvar.setEnabled(false); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        InserirAutor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        InserirLivro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        URL3 = new javax.swing.JLabel();
        InserirGenero = new javax.swing.JTextField();
        InserirData = new javax.swing.JTextField();
        LabelUsuario = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoListagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setText("Varela's Biblioteca");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel20.setText("CADASTRAR LIVRO");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Autor:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Nome do livro:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Data de publicação:");

        URL3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        URL3.setText("Gênero:");

        LabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelUsuario.setText("Nome_do_usuario_e_perfil");
        LabelUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        BotaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoVoltar.setText("<-- Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        BotaoSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoSalvar.setText("CADASTRAR");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        BotaoListagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoListagem.setText("VER LIVROS");
        BotaoListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BotaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoListagem))
                    .addComponent(URL3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InserirAutor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirLivro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirGenero, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirData, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(BotaoVoltar)
                .addGap(70, 70, 70))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(64, 64, 64)
                .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(LabelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(BotaoVoltar))
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InserirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InserirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(InserirData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(URL3)
                .addGap(18, 18, 18)
                .addComponent(InserirGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar)
                    .addComponent(BotaoListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
     
        dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoListagemActionPerformed
        RelatorioLivros rel = new RelatorioLivros(usuario);
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoListagemActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed

         List<String> listaErros = new ArrayList<String>();

         
         String autor = InserirAutor.getText();
         String nomeLivro = InserirLivro.getText();
         String data = InserirData.getText();
         String genero = InserirGenero.getText();
        
         if (autor == null || autor.trim().equals("")) {
             listaErros.add("Informe o autor");   
         }

         if (nomeLivro == null || nomeLivro.trim().equals("")) {
             listaErros.add("Informe o nome do livro");   
         }

         if (genero == null || genero.trim().equals("")) {
             listaErros.add("Informe o genêro do livro");   
         }

         if (data == null || data.trim().equals("")) {
             listaErros.add("Informe a data de publicação");   
         } else if (!data.matches("[0-9]{4}[-][0-9]{2}[-][0-9]{2}")) {
             listaErros.add("Informe a data de publicação no formato aaaa:mm:dd"); 
         }
     
         if (!listaErros.isEmpty()) {
             StringBuilder mensagemErro = new StringBuilder("Para cadastrar um podcast, corrija o(s) erro(s) abaixo:\n\n");

             for (String erro : listaErros) {
                 mensagemErro.append(erro).append("\n");
             }

             JOptionPane.showMessageDialog(this, mensagemErro.toString());
         } else {
             try {               
                 Biblioteca biblioteca = new Biblioteca();
                 biblioteca.setAutor(autor);
                 biblioteca.setnomeLivro(nomeLivro);
                 biblioteca.setdataPublicacao(data);
                 biblioteca.setGenero(genero);
 
                 BibliotecaDAO bibliotecaDAO = new BibliotecaDAO();
                 bibliotecaDAO.cadastrar(biblioteca);  

                 JOptionPane.showMessageDialog(null, "Livro: " + nomeLivro + " cadastrado com sucesso");

                 InserirAutor.setText("");
                 InserirData.setText("");
                 InserirGenero.setText("");
                 InserirLivro.setText("");

                 InserirAutor.requestFocus();
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado ao cadastrar o podcast!!!");
             }
        }
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar(null, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoListagem;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField InserirAutor;
    private javax.swing.JTextField InserirData;
    private javax.swing.JTextField InserirGenero;
    private javax.swing.JTextField InserirLivro;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel URL3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
